name: Lint and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff
        run: uv run ruff check .

  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage for fun
        run: uv run pytest --cov=dbt_fastapi
